#!/usr/bin/env bash

set -e

rm -rf stable-res

ref="${1:-openmw-51-rc2}" 
base_name="openmw-${ref}.0-Linux-64Bit"
#archive_name="${base_name}.tar.gz"
# FIXME: Remove after formal release
archive_name="openmw-0.51.0-Linux-64BitRC2.tar.gz"
#base_url="https://github.com/OpenMW/openmw/releases/download/openmw-${ref}.0/${archive_name}"
# FIXME: Remove after formal release
base_url="https://github.com/OpenMW/openmw/releases/download/openmw-51-rc2/openmw-0.51.0-Linux-64BitRC2.tar.gz"

echo Downloading OpenMW archive for version: ${ref}
wget -q --show-progress -O "${archive_name}" "${base_url}"

echo Extracting resources folder to $(pwd)/stable-res

tar -xzf "${archive_name}" --strip-components=1  "${base_name}/resources"

version_content=$(cat resources/version | tr -d \\r | tr \\n ':')
version_number=$(echo $version_content | cut -f 1 -d ':')
version_commit=$(echo $version_content | cut -f 2 -d ':')

if [[ $GITHUB_ACTIONS ]]; then
  echo "OPENMW_STABLE_VERSION=${version_number}" >> $GITHUB_OUTPUT
  echo "OPENMW_STABLE_COMMIT=${version_commit}" >> $GITHUB_OUTPUT
fi

echo "Cleaning up archive"
rm -f "${archive_name}"

mkdir stable-res
cp -rf resources/vfs-mw/* resources/vfs
rm -rf resources/vfs-mw
mv resources stable-res
