name: Build and Release Resources

on:
    push:
        tags:
            - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile & package resources (for normal humans)
      id: compile
      run: ./compile-resources && ./zip-resources

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *-res-*.zip
        make_latest: true
        body: |
          Freshly baked resource packs - now in civilized ZIP format!
          • Built: ${{ github.run_number }}
          • Commit: ${{ github.sha }}
          • OpenMW Stable: Version: ${{ steps.compile.outputs.OPENMW_STABLE_VERSION }} Commit: [${{ steps.compile.outputs.OPENMW_STABLE_COMMIT }}](https://gitlab.com/OpenMW/openmw/-/commit/${{ steps.compile.outputs.OPENMW_STABLE_COMMIT }})
          • OpenMW Dev: Version: ${{ steps.compile.outputs.OPENMW_DEV_VERSION }} Commit: [${{ steps.compile.outputs.OPENMW_DEV_COMMIT }}](https://gitlab.com/OpenMW/openmw/-/commit/${{ steps.compile.outputs.OPENMW_STABLE_COMMIT }})
